from __future__ import annotations

from .models import RunSpec


def _on_off(value: bool) -> str:
    return "on" if value else "off"


def compile_runspec(spec: RunSpec) -> list[str]:
    lines: list[str] = []

    lines.append("! Auto-generated by backend-api")
    lines.append(f"Main:numberOfEvents = {spec.events}")
    lines.append(f"Main:timesAllowErrors = {spec.times_allow_errors}")

    lines.append(f"Random:setSeed = {_on_off(spec.seed_enabled)}")
    if spec.seed_enabled:
        lines.append(f"Random:seed = {spec.seed}")

    lines.append(f"Beams:frameType = {spec.beam.frame_type}")
    lines.append(f"Beams:idA = {spec.beam.id_a}")
    lines.append(f"Beams:idB = {spec.beam.id_b}")

    if spec.beam.frame_type == 4:
        lines.append(f"Beams:LHEF = {spec.beam.lhef}")
    elif spec.beam.frame_type == 2:
        lines.append(f"Beams:eA = {spec.beam.e_a}")
        lines.append(f"Beams:eB = {spec.beam.e_b}")
    else:
        lines.append(f"Beams:eCM = {spec.beam.e_cm}")

    for key in spec.processes:
        lines.append(f"{key} = on")

    lines.append(f"PhaseSpace:pTHatMin = {spec.phase_space.p_that_min}")
    if spec.phase_space.p_that_max is not None:
        lines.append(f"PhaseSpace:pTHatMax = {spec.phase_space.p_that_max}")
    if spec.phase_space.m_hat_min is not None:
        lines.append(f"PhaseSpace:mHatMin = {spec.phase_space.m_hat_min}")
    if spec.phase_space.m_hat_max is not None:
        lines.append(f"PhaseSpace:mHatMax = {spec.phase_space.m_hat_max}")

    lines.append(f"ProcessLevel:all = {_on_off(spec.event_stages.process_level_all)}")
    lines.append(f"PartonLevel:MPI = {_on_off(spec.event_stages.mpi)}")
    lines.append(f"PartonLevel:ISR = {_on_off(spec.event_stages.isr)}")
    lines.append(f"PartonLevel:FSR = {_on_off(spec.event_stages.fsr)}")
    lines.append(f"HadronLevel:all = {_on_off(spec.event_stages.hadron_all)}")
    lines.append(f"HadronLevel:Hadronize = {_on_off(spec.event_stages.hadronize)}")
    lines.append(f"HadronLevel:Decay = {_on_off(spec.event_stages.decay)}")

    lines.append(f"SpaceShower:pTmaxMatch = {spec.shower_mpi_tune.space_ptmax_match}")
    lines.append(f"TimeShower:pTmaxMatch = {spec.shower_mpi_tune.time_ptmax_match}")
    lines.append(f"MultipartonInteractions:pT0Ref = {spec.shower_mpi_tune.mpi_pt0_ref}")
    lines.append(f"MultipartonInteractions:bProfile = {spec.shower_mpi_tune.mpi_b_profile}")
    lines.append(f"Tune:pp = {spec.shower_mpi_tune.tune_pp}")
    lines.append(f"Tune:ee = {spec.shower_mpi_tune.tune_ee}")

    lines.append(f"PDF:pSet = {spec.pdf_photon.p_set}")
    lines.append(f"PDF:lepton = {_on_off(spec.pdf_photon.lepton)}")
    lines.append(f"PDF:beamA2gamma = {_on_off(spec.pdf_photon.beam_a2gamma)}")
    lines.append(f"PDF:beamB2gamma = {_on_off(spec.pdf_photon.beam_b2gamma)}")
    lines.append(f"PDF:useHard = {_on_off(spec.pdf_photon.use_hard)}")
    lines.append(f"PhotonParton:all = {_on_off(spec.pdf_photon.photon_parton_all)}")

    if spec.merging.enabled:
        lines.append("Merging:doKTMerging = on")
        lines.append(f"Merging:Process = {spec.merging.process}")
        lines.append(f"Merging:TMS = {spec.merging.tms}")
        lines.append(f"Merging:nJetMax = {spec.merging.n_jet_max}")

    if spec.jet_matching.enabled:
        lines.append("JetMatching:merge = on")
        lines.append(f"JetMatching:qCut = {spec.jet_matching.q_cut}")

    if spec.pdg_overrides:
        lines.append("")
        lines.append("! PDG-level overrides")
        for override in spec.pdg_overrides:
            lines.append(f"{override.pdg}:{override.key} = {override.value}")

    if spec.expert_overrides:
        lines.append("")
        lines.append("! Expert overrides")
        lines.extend(spec.expert_overrides)

    return lines


def compile_runspec_to_text(spec: RunSpec) -> str:
    return "\n".join(compile_runspec(spec)).strip() + "\n"
